# Generated by Django 5.1.5 on 2025-01-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="reader",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
